"""종목 리스트 — 자체 포함 데이터 (data/ 폴더 불필요)"""

# 미국 S&P 500 주요 종목
US_TICKERS = [
    ("AAPL", "Apple Inc.", "Technology"),
    ("MSFT", "Microsoft Corp.", "Technology"),
    ("NVDA", "NVIDIA Corp.", "Technology"),
    ("GOOGL", "Alphabet Inc. Class A", "Communication Services"),
    ("GOOG", "Alphabet Inc. Class C", "Communication Services"),
    ("AMZN", "Amazon.com Inc.", "Consumer Discretionary"),
    ("META", "Meta Platforms Inc.", "Communication Services"),
    ("BRK-B", "Berkshire Hathaway Inc.", "Financials"),
    ("LLY", "Eli Lilly and Company", "Health Care"),
    ("AVGO", "Broadcom Inc.", "Technology"),
    ("TSLA", "Tesla Inc.", "Consumer Discretionary"),
    ("JPM", "JPMorgan Chase & Co.", "Financials"),
    ("WMT", "Walmart Inc.", "Consumer Staples"),
    ("V", "Visa Inc.", "Financials"),
    ("XOM", "Exxon Mobil Corp.", "Energy"),
    ("UNH", "UnitedHealth Group Inc.", "Health Care"),
    ("MA", "Mastercard Inc.", "Financials"),
    ("PG", "Procter & Gamble Co.", "Consumer Staples"),
    ("JNJ", "Johnson & Johnson", "Health Care"),
    ("COST", "Costco Wholesale Corp.", "Consumer Staples"),
    ("HD", "Home Depot Inc.", "Consumer Discretionary"),
    ("ORCL", "Oracle Corp.", "Technology"),
    ("ABBV", "AbbVie Inc.", "Health Care"),
    ("BAC", "Bank of America Corp.", "Financials"),
    ("NFLX", "Netflix Inc.", "Communication Services"),
    ("KO", "Coca-Cola Co.", "Consumer Staples"),
    ("CRM", "Salesforce Inc.", "Technology"),
    ("CVX", "Chevron Corp.", "Energy"),
    ("MRK", "Merck & Co. Inc.", "Health Care"),
    ("TMUS", "T-Mobile US Inc.", "Communication Services"),
    ("AMD", "Advanced Micro Devices Inc.", "Technology"),
    ("ADBE", "Adobe Inc.", "Technology"),
    ("PEP", "PepsiCo Inc.", "Consumer Staples"),
    ("CSCO", "Cisco Systems Inc.", "Technology"),
    ("LIN", "Linde plc", "Materials"),
    ("WFC", "Wells Fargo & Co.", "Financials"),
    ("TMO", "Thermo Fisher Scientific Inc.", "Health Care"),
    ("ACN", "Accenture plc", "Technology"),
    ("MCD", "McDonald's Corp.", "Consumer Discretionary"),
    ("ABT", "Abbott Laboratories", "Health Care"),
    ("QCOM", "Qualcomm Inc.", "Technology"),
    ("DHR", "Danaher Corp.", "Health Care"),
    ("GE", "General Electric Co.", "Industrials"),
    ("IBM", "International Business Machines Corp.", "Technology"),
    ("TXN", "Texas Instruments Inc.", "Technology"),
    ("VZ", "Verizon Communications Inc.", "Communication Services"),
    ("INTU", "Intuit Inc.", "Technology"),
    ("PM", "Philip Morris International Inc.", "Consumer Staples"),
    ("AXP", "American Express Co.", "Financials"),
    ("ISRG", "Intuitive Surgical Inc.", "Health Care"),
    ("CAT", "Caterpillar Inc.", "Industrials"),
    ("T", "AT&T Inc.", "Communication Services"),
    ("GS", "Goldman Sachs Group Inc.", "Financials"),
    ("DIS", "Walt Disney Co.", "Communication Services"),
    ("NOW", "ServiceNow Inc.", "Technology"),
    ("RTX", "RTX Corp.", "Industrials"),
    ("PFE", "Pfizer Inc.", "Health Care"),
    ("UBER", "Uber Technologies Inc.", "Industrials"),
    ("NEE", "NextEra Energy Inc.", "Utilities"),
    ("SPGI", "S&P Global Inc.", "Financials"),
    ("LOW", "Lowe's Companies Inc.", "Consumer Discretionary"),
    ("AMGN", "Amgen Inc.", "Health Care"),
    ("UNP", "Union Pacific Corp.", "Industrials"),
    ("HON", "Honeywell International Inc.", "Industrials"),
    ("SYK", "Stryker Corp.", "Health Care"),
    ("PGR", "Progressive Corp.", "Financials"),
    ("ETN", "Eaton Corp. plc", "Industrials"),
    ("TJX", "TJX Companies Inc.", "Consumer Discretionary"),
    ("BLK", "BlackRock Inc.", "Financials"),
    ("COP", "ConocoPhillips", "Energy"),
    ("BSX", "Boston Scientific Corp.", "Health Care"),
    ("C", "Citigroup Inc.", "Financials"),
    ("VRTX", "Vertex Pharmaceuticals Inc.", "Health Care"),
    ("PANW", "Palo Alto Networks Inc.", "Technology"),
    ("SCHW", "Charles Schwab Corp.", "Financials"),
    ("ANET", "Arista Networks Inc.", "Technology"),
    ("PLD", "Prologis Inc.", "Real Estate"),
    ("MS", "Morgan Stanley", "Financials"),
    ("ADP", "Automatic Data Processing Inc.", "Industrials"),
    ("ADI", "Analog Devices Inc.", "Technology"),
    ("TT", "Trane Technologies plc", "Industrials"),
    ("GILD", "Gilead Sciences Inc.", "Health Care"),
    ("MU", "Micron Technology Inc.", "Technology"),
    ("LRCX", "Lam Research Corp.", "Technology"),
    ("KLAC", "KLA Corp.", "Technology"),
    ("DE", "Deere & Co.", "Industrials"),
    ("MDLZ", "Mondelez International Inc.", "Consumer Staples"),
    ("INTC", "Intel Corp.", "Technology"),
    ("LMT", "Lockheed Martin Corp.", "Industrials"),
    ("REGN", "Regeneron Pharmaceuticals Inc.", "Health Care"),
    ("ELV", "Elevance Health Inc.", "Health Care"),
    ("BX", "Blackstone Inc.", "Financials"),
    ("SBUX", "Starbucks Corp.", "Consumer Discretionary"),
    ("CB", "Chubb Ltd.", "Financials"),
    ("KKR", "KKR & Co. Inc.", "Financials"),
    ("CMCSA", "Comcast Corp.", "Communication Services"),
    ("NKE", "Nike Inc.", "Consumer Discretionary"),
    ("AMAT", "Applied Materials Inc.", "Technology"),
    ("MMC", "Marsh & McLennan Companies Inc.", "Financials"),
    ("CI", "Cigna Group", "Health Care"),
    ("SO", "Southern Co.", "Utilities"),
    ("BMY", "Bristol-Myers Squibb Co.", "Health Care"),
    ("ICE", "Intercontinental Exchange Inc.", "Financials"),
    ("MO", "Altria Group Inc.", "Consumer Staples"),
    ("SHW", "Sherwin-Williams Co.", "Materials"),
    ("DUK", "Duke Energy Corp.", "Utilities"),
    ("PH", "Parker-Hannifin Corp.", "Industrials"),
    ("ZTS", "Zoetis Inc.", "Health Care"),
    ("EQIX", "Equinix Inc.", "Real Estate"),
    ("PYPL", "PayPal Holdings Inc.", "Financials"),
    ("CDNS", "Cadence Design Systems Inc.", "Technology"),
    ("WM", "Waste Management Inc.", "Industrials"),
    ("APH", "Amphenol Corp.", "Technology"),
    ("USB", "U.S. Bancorp", "Financials"),
    ("SNPS", "Synopsys Inc.", "Technology"),
    ("ITW", "Illinois Tool Works Inc.", "Industrials"),
    ("CME", "CME Group Inc.", "Financials"),
    ("MCO", "Moody's Corp.", "Financials"),
    ("PNC", "PNC Financial Services Group Inc.", "Financials"),
    ("CL", "Colgate-Palmolive Co.", "Consumer Staples"),
    ("TDG", "TransDigm Group Inc.", "Industrials"),
    ("CRWD", "CrowdStrike Holdings Inc.", "Technology"),
    ("EOG", "EOG Resources Inc.", "Energy"),
    ("WELL", "Welltower Inc.", "Real Estate"),
    ("APD", "Air Products and Chemicals Inc.", "Materials"),
    ("MDT", "Medtronic plc", "Health Care"),
    ("ECL", "Ecolab Inc.", "Materials"),
    ("GD", "General Dynamics Corp.", "Industrials"),
    ("EMR", "Emerson Electric Co.", "Industrials"),
    ("MMM", "3M Co.", "Industrials"),
    ("ORLY", "O'Reilly Automotive Inc.", "Consumer Discretionary"),
    ("COF", "Capital One Financial Corp.", "Financials"),
    ("NOC", "Northrop Grumman Corp.", "Industrials"),
    ("MAR", "Marriott International Inc.", "Consumer Discretionary"),
    ("AON", "Aon plc", "Financials"),
    ("TGT", "Target Corp.", "Consumer Discretionary"),
    ("CSX", "CSX Corp.", "Industrials"),
    ("WMB", "Williams Companies Inc.", "Energy"),
    ("APO", "Apollo Global Management Inc.", "Financials"),
    ("FDX", "FedEx Corp.", "Industrials"),
    ("BDX", "Becton Dickinson and Co.", "Health Care"),
    ("NSC", "Norfolk Southern Corp.", "Industrials"),
    ("HCA", "HCA Healthcare Inc.", "Health Care"),
    ("MCK", "McKesson Corp.", "Health Care"),
    ("GM", "General Motors Co.", "Consumer Discretionary"),
    ("PCAR", "PACCAR Inc.", "Industrials"),
    ("ROP", "Roper Technologies Inc.", "Industrials"),
    ("F", "Ford Motor Co.", "Consumer Discretionary"),
    ("FCX", "Freeport-McMoRan Inc.", "Materials"),
    ("SRE", "Sempra", "Utilities"),
    ("NEM", "Newmont Corp.", "Materials"),
    ("TFC", "Truist Financial Corp.", "Financials"),
    ("PSA", "Public Storage", "Real Estate"),
    ("ABNB", "Airbnb Inc.", "Consumer Discretionary"),
    ("NXPI", "NXP Semiconductors NV", "Technology"),
    ("AJG", "Arthur J. Gallagher & Co.", "Financials"),
    ("URI", "United Rentals Inc.", "Industrials"),
    ("AIG", "American International Group Inc.", "Financials"),
    ("CARR", "Carrier Global Corp.", "Industrials"),
    ("AFL", "Aflac Inc.", "Financials"),
    ("SLB", "Schlumberger NV", "Energy"),
    ("TRV", "Travelers Companies Inc.", "Financials"),
    ("HLT", "Hilton Worldwide Holdings Inc.", "Consumer Discretionary"),
    ("PSX", "Phillips 66", "Energy"),
    ("MET", "MetLife Inc.", "Financials"),
    ("AZO", "AutoZone Inc.", "Consumer Discretionary"),
    ("ROST", "Ross Stores Inc.", "Consumer Discretionary"),
    ("KMB", "Kimberly-Clark Corp.", "Consumer Staples"),
    ("BK", "Bank of New York Mellon Corp.", "Financials"),
    ("PCG", "PG&E Corp.", "Utilities"),
    ("PAYX", "Paychex Inc.", "Industrials"),
    ("SPG", "Simon Property Group Inc.", "Real Estate"),
    ("CMG", "Chipotle Mexican Grill Inc.", "Consumer Discretionary"),
    ("DELL", "Dell Technologies Inc.", "Technology"),
    ("GWW", "W.W. Grainger Inc.", "Industrials"),
    ("TEL", "TE Connectivity Ltd.", "Technology"),
    ("KMI", "Kinder Morgan Inc.", "Energy"),
    ("DLR", "Digital Realty Trust Inc.", "Real Estate"),
    ("O", "Realty Income Corp.", "Real Estate"),
    ("MSI", "Motorola Solutions Inc.", "Technology"),
    ("FTNT", "Fortinet Inc.", "Technology"),
    ("HUM", "Humana Inc.", "Health Care"),
    ("COR", "Cencora Inc.", "Health Care"),
    ("AEP", "American Electric Power Co.", "Utilities"),
    ("KDP", "Keurig Dr Pepper Inc.", "Consumer Staples"),
    ("ROK", "Rockwell Automation Inc.", "Industrials"),
    ("PRU", "Prudential Financial Inc.", "Financials"),
    ("GIS", "General Mills Inc.", "Consumer Staples"),
    ("DASH", "DoorDash Inc.", "Consumer Discretionary"),
    ("KHC", "Kraft Heinz Co.", "Consumer Staples"),
    ("LHX", "L3Harris Technologies Inc.", "Industrials"),
    ("COIN", "Coinbase Global Inc.", "Financials"),
    ("OXY", "Occidental Petroleum Corp.", "Energy"),
    ("EXC", "Exelon Corp.", "Utilities"),
    ("KVUE", "Kenvue Inc.", "Consumer Staples"),
    ("EW", "Edwards Lifesciences Corp.", "Health Care"),
    ("KR", "Kroger Co.", "Consumer Staples"),
    ("SYY", "Sysco Corp.", "Consumer Staples"),
    ("CCI", "Crown Castle Inc.", "Real Estate"),
    ("HES", "Hess Corp.", "Energy"),
    ("FAST", "Fastenal Co.", "Industrials"),
    ("HSY", "Hershey Co.", "Consumer Staples"),
    ("FANG", "Diamondback Energy Inc.", "Energy"),
    ("ODFL", "Old Dominion Freight Line Inc.", "Industrials"),
    ("NUE", "Nucor Corp.", "Materials"),
    ("WBA", "Walgreens Boots Alliance Inc.", "Consumer Staples"),
    ("DOW", "Dow Inc.", "Materials"),
    ("GEHC", "GE HealthCare Technologies Inc.", "Health Care"),
    ("A", "Agilent Technologies Inc.", "Health Care"),
    ("LULU", "Lululemon Athletica Inc.", "Consumer Discretionary"),
    ("DXCM", "DexCom Inc.", "Health Care"),
    ("IT", "Gartner Inc.", "Technology"),
    ("FIS", "Fidelity National Information Services Inc.", "Technology"),
    ("XEL", "Xcel Energy Inc.", "Utilities"),
    ("IR", "Ingersoll Rand Inc.", "Industrials"),
    ("HAL", "Halliburton Co.", "Energy"),
    ("CPRT", "Copart Inc.", "Industrials"),
    ("GLW", "Corning Inc.", "Technology"),
    ("ALL", "Allstate Corp.", "Financials"),
    ("EA", "Electronic Arts Inc.", "Communication Services"),
    ("CTAS", "Cintas Corp.", "Industrials"),
    ("RSG", "Republic Services Inc.", "Industrials"),
    ("GRMN", "Garmin Ltd.", "Consumer Discretionary"),
    ("VRSK", "Verisk Analytics Inc.", "Industrials"),
    ("PEG", "Public Service Enterprise Group Inc.", "Utilities"),
    ("OTIS", "Otis Worldwide Corp.", "Industrials"),
    ("MNST", "Monster Beverage Corp.", "Consumer Staples"),
    ("YUM", "Yum! Brands Inc.", "Consumer Discretionary"),
    ("WTW", "Willis Towers Watson plc", "Financials"),
    ("GEV", "GE Vernova Inc.", "Industrials"),
    ("HPQ", "HP Inc.", "Technology"),
    ("DDOG", "Datadog Inc.", "Technology"),
    ("EQR", "Equity Residential", "Real Estate"),
    ("BKR", "Baker Hughes Co.", "Energy"),
    ("EXR", "Extra Space Storage Inc.", "Real Estate"),
    ("EBAY", "eBay Inc.", "Consumer Discretionary"),
    ("CTSH", "Cognizant Technology Solutions Corp.", "Technology"),
    ("RCL", "Royal Caribbean Cruises Ltd.", "Consumer Discretionary"),
    ("WAB", "Westinghouse Air Brake Technologies Corp.", "Industrials"),
    ("AME", "Ametek Inc.", "Industrials"),
    ("CHTR", "Charter Communications Inc.", "Communication Services"),
    ("NDAQ", "Nasdaq Inc.", "Financials"),
    ("ED", "Consolidated Edison Inc.", "Utilities"),
    ("WEC", "WEC Energy Group Inc.", "Utilities"),
    ("IRM", "Iron Mountain Inc.", "Real Estate"),
    ("ETR", "Entergy Corp.", "Utilities"),
    ("VST", "Vistra Corp.", "Utilities"),
    ("HIG", "Hartford Financial Services Group Inc.", "Financials"),
    ("CSGP", "CoStar Group Inc.", "Real Estate"),
    ("TRGP", "Targa Resources Corp.", "Energy"),
    ("STZ", "Constellation Brands Inc.", "Consumer Staples"),
    ("DAL", "Delta Air Lines Inc.", "Industrials"),
    ("EFX", "Equifax Inc.", "Industrials"),
    ("MLM", "Martin Marietta Materials Inc.", "Materials"),
    ("ANSS", "ANSYS Inc.", "Technology"),
    ("KEYS", "Keysight Technologies Inc.", "Technology"),
    ("WBD", "Warner Bros. Discovery Inc.", "Communication Services"),
    ("AVB", "AvalonBay Communities Inc.", "Real Estate"),
    ("VMC", "Vulcan Materials Co.", "Materials"),
    ("LYV", "Live Nation Entertainment Inc.", "Communication Services"),
    ("RJF", "Raymond James Financial Inc.", "Financials"),
    ("DFS", "Discover Financial Services", "Financials"),
    ("TSCO", "Tractor Supply Co.", "Consumer Discretionary"),
    ("WY", "Weyerhaeuser Co.", "Real Estate"),
    ("DVN", "Devon Energy Corp.", "Energy"),
    ("HPE", "Hewlett Packard Enterprise Co.", "Technology"),
    ("PPG", "PPG Industries Inc.", "Materials"),
    ("ON", "ON Semiconductor Corp.", "Technology"),
    ("IDXX", "IDEXX Laboratories Inc.", "Health Care"),
    ("FITB", "Fifth Third Bancorp", "Financials"),
    ("BRO", "Brown & Brown Inc.", "Financials"),
    ("DOV", "Dover Corp.", "Industrials"),
    ("MPWR", "Monolithic Power Systems Inc.", "Technology"),
    ("GPN", "Global Payments Inc.", "Financials"),
    ("TROW", "T. Rowe Price Group Inc.", "Financials"),
    ("HUBB", "Hubbell Inc.", "Industrials"),
    ("FTV", "Fortive Corp.", "Industrials"),
    ("PWR", "Quanta Services Inc.", "Industrials"),
    ("HBAN", "Huntington Bancshares Inc.", "Financials"),
    ("GPC", "Genuine Parts Co.", "Consumer Discretionary"),
    ("RF", "Regions Financial Corp.", "Financials"),
    ("TTWO", "Take-Two Interactive Software Inc.", "Communication Services"),
    ("ROL", "Rollins Inc.", "Industrials"),
    ("TDY", "Teledyne Technologies Inc.", "Industrials"),
    ("ZBRA", "Zebra Technologies Corp.", "Technology"),
    ("ATO", "Atmos Energy Corp.", "Utilities"),
    ("BIIB", "Biogen Inc.", "Health Care"),
    ("INVH", "Invitation Homes Inc.", "Real Estate"),
    ("NTAP", "NetApp Inc.", "Technology"),
    ("ZBH", "Zimmer Biomet Holdings Inc.", "Health Care"),
    ("MTB", "M&T Bank Corp.", "Financials"),
    ("ULTA", "Ulta Beauty Inc.", "Consumer Discretionary"),
    ("DRI", "Darden Restaurants Inc.", "Consumer Discretionary"),
    ("TYL", "Tyler Technologies Inc.", "Technology"),
    ("NVR", "NVR Inc.", "Consumer Discretionary"),
    ("MKC", "McCormick & Co. Inc.", "Consumer Staples"),
    ("MTD", "Mettler-Toledo International Inc.", "Health Care"),
    ("FCNCA", "First Citizens BancShares Inc.", "Financials"),
    ("PHM", "PulteGroup Inc.", "Consumer Discretionary"),
    ("PPL", "PPL Corp.", "Utilities"),
    ("ARE", "Alexandria Real Estate Equities Inc.", "Real Estate"),
    ("WAT", "Waters Corp.", "Health Care"),
    ("LDOS", "Leidos Holdings Inc.", "Industrials"),
    ("LH", "Labcorp Holdings Inc.", "Health Care"),
    ("BR", "Broadridge Financial Solutions Inc.", "Industrials"),
    ("ES", "Eversource Energy", "Utilities"),
    ("STT", "State Street Corp.", "Financials"),
    ("PTC", "PTC Inc.", "Technology"),
    ("LEN", "Lennar Corp.", "Consumer Discretionary"),
    ("DHI", "D.R. Horton Inc.", "Consumer Discretionary"),
    ("TPL", "Texas Pacific Land Corp.", "Energy"),
    ("HOLX", "Hologic Inc.", "Health Care"),
    ("BAX", "Baxter International Inc.", "Health Care"),
    ("VLO", "Valero Energy Corp.", "Energy"),
    ("NTRS", "Northern Trust Corp.", "Financials"),
    ("CTRA", "Coterra Energy Inc.", "Energy"),
    ("WSM", "Williams-Sonoma Inc.", "Consumer Discretionary"),
    ("CINF", "Cincinnati Financial Corp.", "Financials"),
    ("DPZ", "Domino's Pizza Inc.", "Consumer Discretionary"),
    ("WST", "West Pharmaceutical Services Inc.", "Health Care"),
    ("PFG", "Principal Financial Group Inc.", "Financials"),
    ("EXPE", "Expedia Group Inc.", "Consumer Discretionary"),
    ("SBAC", "SBA Communications Corp.", "Real Estate"),
    ("FE", "FirstEnergy Corp.", "Utilities"),
    ("NRG", "NRG Energy Inc.", "Utilities"),
    ("ESS", "Essex Property Trust Inc.", "Real Estate"),
    ("TER", "Teradyne Inc.", "Technology"),
    ("DG", "Dollar General Corp.", "Consumer Staples"),
    ("LYB", "LyondellBasell Industries NV", "Materials"),
    ("LVS", "Las Vegas Sands Corp.", "Consumer Discretionary"),
    ("SMCI", "Super Micro Computer Inc.", "Technology"),
    ("J", "Jacobs Solutions Inc.", "Industrials"),
    ("EXPD", "Expeditors International of Washington Inc.", "Industrials"),
    ("STE", "STERIS plc", "Health Care"),
    ("EIX", "Edison International", "Utilities"),
    ("PLTR", "Palantir Technologies Inc.", "Technology"),
    ("SNOW", "Snowflake Inc.", "Technology"),
    ("SHOP", "Shopify Inc.", "Technology"),
    ("BABA", "Alibaba Group Holding Ltd.", "Consumer Discretionary"),
    ("SQ", "Block Inc.", "Financials"),
    ("PINS", "Pinterest Inc.", "Communication Services"),
    ("RBLX", "Roblox Corp.", "Communication Services"),
    ("HOOD", "Robinhood Markets Inc.", "Financials"),
    ("PLUG", "Plug Power Inc.", "Industrials"),
    ("RIVN", "Rivian Automotive Inc.", "Consumer Discretionary"),
    ("LCID", "Lucid Group Inc.", "Consumer Discretionary"),
    ("SOFI", "SoFi Technologies Inc.", "Financials"),
    ("NIO", "NIO Inc.", "Consumer Discretionary"),
    ("ASML", "ASML Holding NV", "Technology"),
    ("TSM", "Taiwan Semiconductor Manufacturing Co.", "Technology"),
    ("SE", "Sea Ltd.", "Communication Services"),
    ("MELI", "MercadoLibre Inc.", "Consumer Discretionary"),
    ("NU", "Nu Holdings Ltd.", "Financials"),
    ("ARM", "Arm Holdings plc", "Technology"),
    ("JNPR", "Juniper Networks Inc.", "Technology"),
    ("ALGN", "Align Technology Inc.", "Health Care"),
    ("ENPH", "Enphase Energy Inc.", "Information Technology"),
    ("FSLR", "First Solar Inc.", "Technology"),
    ("DOCU", "DocuSign Inc.", "Technology"),
    ("ZS", "Zscaler Inc.", "Technology"),
    ("NET", "Cloudflare Inc.", "Technology"),
    ("OKTA", "Okta Inc.", "Technology"),
    ("MDB", "MongoDB Inc.", "Technology"),
    ("TEAM", "Atlassian Corp.", "Technology"),
    ("WDAY", "Workday Inc.", "Technology"),
    ("ADSK", "Autodesk Inc.", "Technology"),
]

# 한국 KOSPI/KOSDAQ 주요 종목
KR_TICKERS = [
    ("005930.KS", "삼성전자", "반도체"),
    ("000660.KS", "SK하이닉스", "반도체"),
    ("373220.KS", "LG에너지솔루션", "2차전지"),
    ("207940.KS", "삼성바이오로직스", "바이오"),
    ("005380.KS", "현대차", "자동차"),
    ("005935.KS", "삼성전자우", "반도체"),
    ("068270.KS", "셀트리온", "바이오"),
    ("000270.KS", "기아", "자동차"),
    ("035420.KS", "NAVER", "인터넷"),
    ("105560.KS", "KB금융", "금융"),
    ("055550.KS", "신한지주", "금융"),
    ("006400.KS", "삼성SDI", "2차전지"),
    ("028260.KS", "삼성물산", "상사"),
    ("012330.KS", "현대모비스", "자동차부품"),
    ("066570.KS", "LG전자", "가전"),
    ("003670.KS", "포스코홀딩스", "철강"),
    ("035720.KS", "카카오", "인터넷"),
    ("015760.KS", "한국전력", "전력"),
    ("017670.KS", "SK텔레콤", "통신"),
    ("032830.KS", "삼성생명", "보험"),
    ("138040.KS", "메리츠금융지주", "금융"),
    ("086790.KS", "하나금융지주", "금융"),
    ("033780.KS", "KT&G", "담배"),
    ("009150.KS", "삼성전기", "전자부품"),
    ("402340.KS", "SK스퀘어", "투자"),
    ("018260.KS", "삼성에스디에스", "IT서비스"),
    ("316140.KS", "우리금융지주", "금융"),
    ("259960.KS", "크래프톤", "게임"),
    ("000810.KS", "삼성화재", "보험"),
    ("024110.KS", "기업은행", "금융"),
    ("010130.KS", "고려아연", "비철금속"),
    ("011200.KS", "HMM", "해운"),
    ("267260.KS", "HD현대일렉트릭", "중공업"),
    ("034730.KS", "SK", "지주사"),
    ("009540.KS", "HD한국조선해양", "조선"),
    ("030200.KS", "KT", "통신"),
    ("377300.KS", "카카오페이", "핀테크"),
    ("267250.KS", "HD현대", "조선"),
    ("000720.KS", "현대건설", "건설"),
    ("018880.KS", "한온시스템", "자동차부품"),
    ("036570.KS", "엔씨소프트", "게임"),
    ("003550.KS", "LG", "지주사"),
    ("047810.KS", "한국항공우주", "항공우주"),
    ("010950.KS", "S-Oil", "정유"),
    ("352820.KS", "하이브", "엔터테인먼트"),
    ("011170.KS", "롯데케미칼", "화학"),
    ("161390.KS", "한국타이어앤테크놀로지", "자동차부품"),
    ("241560.KS", "두산밥캣", "중공업"),
    ("006800.KS", "미래에셋증권", "증권"),
    ("078930.KS", "GS", "지주사"),
    ("139480.KS", "이마트", "유통"),
    ("000100.KS", "유한양행", "제약"),
    ("032640.KS", "LG유플러스", "통신"),
    ("047050.KS", "포스코인터내셔널", "상사"),
    ("088980.KS", "맥쿼리인프라", "인프라"),
    ("009830.KS", "한화솔루션", "화학"),
    ("180640.KS", "한진칼", "항공"),
    ("081660.KS", "휠라홀딩스", "섬유의복"),
    ("000990.KS", "DB하이텍", "반도체"),
    ("021240.KS", "코웨이", "가전"),
    ("326030.KS", "SK바이오팜", "바이오"),
    ("036460.KS", "한국가스공사", "가스"),
    ("051910.KS", "LG화학", "화학"),
    ("064350.KS", "현대로템", "철도"),
    ("028050.KS", "삼성E&A", "건설"),
    ("000150.KS", "두산", "지주사"),
    ("006360.KS", "GS건설", "건설"),
    ("010620.KS", "HD현대미포", "조선"),
    ("023530.KS", "롯데쇼핑", "유통"),
    ("271560.KS", "오리온", "식음료"),
    ("047040.KS", "대우건설", "건설"),
    ("004020.KS", "현대제철", "철강"),
    ("008770.KS", "호텔신라", "호텔"),
    ("003490.KS", "대한항공", "항공"),
    ("042660.KS", "한화오션", "조선"),
    ("008560.KS", "메리츠증권", "증권"),
    ("192820.KS", "코스맥스", "화장품"),
    ("375500.KS", "DL이앤씨", "건설"),
    ("003410.KS", "쌍용씨앤이", "시멘트"),
    ("204320.KS", "HL만도", "자동차부품"),
    ("185750.KS", "종근당", "제약"),
    ("112610.KS", "CS윈드", "재생에너지"),
    ("035250.KS", "강원랜드", "레저"),
    ("000060.KS", "메리츠화재", "보험"),
    ("008930.KS", "한미사이언스", "제약"),
    ("028670.KS", "팬오션", "해운"),
    ("001040.KS", "CJ", "지주사"),
    ("000080.KS", "하이트진로", "식음료"),
    ("097950.KS", "CJ제일제당", "식음료"),
    ("000120.KS", "CJ대한통운", "물류"),
    ("003230.KS", "삼양식품", "식음료"),
    ("006040.KS", "동원산업", "수산"),
    ("004990.KS", "롯데지주", "지주사"),
    ("009240.KS", "한샘", "가구"),
    ("161890.KS", "한국콜마", "화장품"),
    ("090430.KS", "아모레퍼시픽", "화장품"),
    ("036420.KS", "제이콘텐트리", "미디어"),
    ("007310.KS", "오뚜기", "식음료"),
    ("196170.KQ", "알테오젠", "바이오"),
    ("247540.KQ", "에코프로비엠", "2차전지"),
    ("086520.KQ", "에코프로", "2차전지"),
    ("091990.KQ", "셀트리온헬스케어", "바이오"),
    ("066970.KQ", "엘앤에프", "2차전지"),
    ("028300.KQ", "HLB", "바이오"),
    ("277810.KQ", "레인보우로보틱스", "로봇"),
    ("328130.KQ", "루닛", "헬스케어"),
    ("240810.KQ", "원익IPS", "반도체장비"),
    ("035900.KQ", "JYP Ent.", "엔터테인먼트"),
    ("214150.KQ", "클래시스", "의료기기"),
    ("357780.KQ", "솔브레인", "반도체소재"),
    ("039030.KQ", "이오테크닉스", "반도체장비"),
    ("067310.KQ", "하나마이크론", "반도체"),
    ("041510.KQ", "SM", "엔터테인먼트"),
    ("141080.KQ", "리가켐바이오", "바이오"),
    ("122870.KQ", "와이지엔터테인먼트", "엔터테인먼트"),
    ("064760.KQ", "티씨케이", "반도체소재"),
    ("348370.KQ", "엔켐", "2차전지"),
    ("036930.KQ", "주성엔지니어링", "반도체장비"),
    ("395400.KQ", "SK이터닉스", "재생에너지"),
    ("000250.KQ", "삼천당제약", "제약"),
    ("095340.KQ", "ISC", "반도체장비"),
    ("112040.KQ", "위메이드", "게임"),
    ("293490.KQ", "카카오게임즈", "게임"),
    ("039200.KQ", "오스코텍", "바이오"),
    ("035600.KQ", "KG이니시스", "핀테크"),
    ("094840.KQ", "슈프리마", "보안"),
    ("278280.KQ", "천보", "화학"),
    ("017960.KQ", "한국카본", "화학"),
    ("035760.KQ", "CJ ENM", "미디어"),
    ("145020.KQ", "휴젤", "바이오"),
    ("108860.KQ", "셀바스AI", "AI"),
    ("060280.KQ", "큐렉소", "의료기기"),
    ("357550.KQ", "석경에이티", "소재"),
    ("448730.KQ", "SK오션플랜트", "중공업"),
    ("178320.KQ", "서진시스템", "통신장비"),
    ("214370.KQ", "케어젠", "바이오"),
    ("083650.KQ", "비에이치아이", "발전설비"),
    ("078340.KQ", "컴투스", "게임"),
    ("039840.KQ", "디오", "의료기기"),
    ("137310.KQ", "에스디바이오센서", "진단키트"),
    ("214450.KQ", "파마리서치", "바이오"),
    ("067160.KQ", "아프리카TV", "미디어"),
    ("089030.KQ", "테크윙", "반도체장비"),
    ("084990.KQ", "헬릭스미스", "바이오"),
    ("041190.KQ", "우리기술투자", "투자"),
    ("053610.KQ", "프로텍", "반도체장비"),
    ("018290.KQ", "브이엠", "반도체장비"),
    ("357230.KQ", "파나시아", "환경"),
    ("196300.KQ", "위지트", "반도체"),
    ("299900.KQ", "위지윅스튜디오", "영상"),
    ("032580.KQ", "피델릭스", "반도체"),
    ("041910.KQ", "에스텍파마", "제약"),
    ("036540.KQ", "에스엔에스", "게임"),
    ("083790.KQ", "크리스탈지노믹스", "바이오"),
    ("299030.KQ", "하나기술", "반도체장비"),
    ("352480.KQ", "씨이랩", "AI"),
    ("084370.KQ", "유진테크", "반도체장비"),
    ("194480.KQ", "데브시스터즈", "게임"),
    ("192440.KQ", "슈피겐코리아", "IT"),
    ("085660.KQ", "차바이오텍", "바이오"),
    ("067290.KQ", "JW신약", "제약"),
    ("053800.KQ", "안랩", "보안"),
    ("084850.KQ", "에이프로젠메디신", "바이오"),
    ("237880.KQ", "클리오", "화장품"),
    ("023460.KQ", "이엠앤아이", "IT"),
]

# 산업 스토리 폴백 DB
SECTOR_STORIES = {'sector_stories': {'Technology': {'growth_drivers': 'AI/클라우드 인프라 수요 · 디지털 전환 · 반도체 사이클', 'moat_pattern': '기술 격차 · 네트워크 효과 · 전환 비용 · 데이터 축적', 'default_industry': '소프트웨어/하드웨어/반도체'}, 'Communication Services': {'growth_drivers': '디지털 광고 · 스트리밍 가입자 · AI 콘텐츠 · 통신 인프라', 'moat_pattern': '사용자 네트워크 효과 · 콘텐츠 라이브러리 · 주파수 라이선스', 'default_industry': '광고/스트리밍/통신'}, 'Consumer Discretionary': {'growth_drivers': '소비 회복 · 프리미엄화 · E커머스 · 여행 수요 회복', 'moat_pattern': '브랜드 가치 · 유통망 · 멤버십/회원 락인', 'default_industry': '유통/소비재/여행'}, 'Consumer Staples': {'growth_drivers': '필수재 가격 결정력 · 신흥국 소비 확대 · 프리미엄 카테고리', 'moat_pattern': '강력한 브랜드 · 유통 채널 장악 · 규모의 경제', 'default_industry': '식음료/생활용품'}, 'Financials': {'growth_drivers': '금리 환경 · 자본시장 활성화 · 핀테크 전환 · 자산운용 규모', 'moat_pattern': '자본 규모 · 라이선스 진입장벽 · 고객 신뢰', 'default_industry': '은행/보험/자산운용'}, 'Health Care': {'growth_drivers': '고령화 · 신약 파이프라인 · 의료기기 혁신 · 비만·당뇨 치료제', 'moat_pattern': '특허 · 임상 데이터 · 규제 진입장벽 · R&D 파이프라인', 'default_industry': '제약/의료기기/바이오'}, 'Industrials': {'growth_drivers': '인프라 투자 · 리쇼어링 · 방산 수요 · 자동화·로봇', 'moat_pattern': '장기 계약 · 기술 표준 · 규모의 경제 · 정부 발주', 'default_industry': '제조/항공우주/물류'}, 'Energy': {'growth_drivers': '유가 사이클 · 에너지 안보 · LNG 수출 · 재생에너지 전환', 'moat_pattern': '매장량 · 인프라(파이프라인/터미널) · 통합 밸류체인', 'default_industry': '정유/탐사/유틸리티'}, 'Utilities': {'growth_drivers': '전력 수요(AI 데이터센터) · 재생에너지 전환 · 요금 인상', 'moat_pattern': '지역 독점 · 규제 보호 · 대규모 인프라 자산', 'default_industry': '전력/가스/수도'}, 'Real Estate': {'growth_drivers': '금리 하락 · 데이터센터 REIT · 물류 부동산 · 임대료 상승', 'moat_pattern': '입지 · 장기 임대 · 자산 규모', 'default_industry': '리츠/부동산'}, 'Materials': {'growth_drivers': '원자재 사이클 · 인프라 수요 · 2차전지 소재 · 친환경 전환', 'moat_pattern': '매장량 · 생산비용 우위 · 통합 공급망', 'default_industry': '금속/화학/건설자재'}}, 'korea_sector_stories': {'반도체': {'growth_drivers': 'AI 메모리(HBM) 수요 · 데이터센터 투자 · 파운드리 경쟁', 'moat_pattern': '기술 격차(공정·수율) · CAPEX 진입장벽 · 고객 락인'}, '2차전지': {'growth_drivers': '전기차 침투율 확대 · ESS 시장 · 양극재/소재 내재화', 'moat_pattern': '장기 공급계약 · 생산 캐파 · 소재 수직계열화'}, '바이오': {'growth_drivers': '신약 파이프라인 · 바이오시밀러 · CDMO 수주', 'moat_pattern': '임상 데이터 · 특허 · 생산 캐파(시밀러/CDMO)'}, '자동차': {'growth_drivers': '전기차 전환 · 글로벌 점유율 · 프리미엄화', 'moat_pattern': '브랜드 · 글로벌 생산기지 · 부품 수직계열화'}, '자동차부품': {'growth_drivers': '전기차 부품 수요 · 자율주행 · 글로벌 OEM 수주', 'moat_pattern': '장기 납품계약 · 기술 인증 · 고객 락인'}, '조선': {'growth_drivers': 'LNG선·친환경선 수주 · 신조선가 상승 · 방산 수출', 'moat_pattern': '기술력(LNG·고부가선) · 도크 캐파 · 장기 수주잔고'}, '철강': {'growth_drivers': '인프라 수요 · 친환경 전환(수소환원제철) · 가격 회복', 'moat_pattern': '원가 경쟁력 · 통합 생산 · 내수 점유율'}, '화학': {'growth_drivers': '스페셜티 화학 전환 · 2차전지 소재 · 다운사이클 회복', 'moat_pattern': '원료 통합 · 스페셜티 포트폴리오 · 규모'}, '금융': {'growth_drivers': '금리 환경 · 자산운용 · 디지털 전환 · 동남아 진출', 'moat_pattern': '고객 기반 · 자본 규모 · 라이선스'}, '보험': {'growth_drivers': '고령화 · IFRS17 안정화 · 자산운용 수익', 'moat_pattern': '장기 계약 · 자산 규모 · 보험 라이선스'}, '증권': {'growth_drivers': '자본시장 거래 · IB 수수료 · 자산관리(WM)', 'moat_pattern': '트레이딩 인프라 · 고객 네트워크 · 자본력'}, '통신': {'growth_drivers': '5G/6G 투자 · B2B(클라우드/IDC) · 콘텐츠 확장', 'moat_pattern': '주파수 라이선스 · 망 인프라 · 가입자 기반'}, '인터넷': {'growth_drivers': 'AI 서비스 확장 · 광고 · 커머스 · 콘텐츠', 'moat_pattern': '사용자 네트워크 · 데이터 · 검색/메신저 점유율'}, '게임': {'growth_drivers': '신작 사이클 · 글로벌 출시 · IP 확장', 'moat_pattern': '히트 IP · 개발력 · 글로벌 퍼블리싱 채널'}, '엔터테인먼트': {'growth_drivers': 'K-콘텐츠 글로벌화 · 아티스트 IP · 라이브 공연 회복', 'moat_pattern': '아티스트 IP · 글로벌 팬덤 · 제작 노하우'}, '유통': {'growth_drivers': 'e커머스 전환 · 프리미엄화 · 신선식품 채널', 'moat_pattern': '점포망 · 물류 인프라 · 멤버십'}, '식음료': {'growth_drivers': '프리미엄/건강 카테고리 · 해외 진출 · 가격 인상', 'moat_pattern': '브랜드 · 유통망 · R&D'}, '화장품': {'growth_drivers': 'K-뷰티 글로벌 확장 · 인디 브랜드 · 더마 코스메틱', 'moat_pattern': '브랜드 · ODM/제조 역량 · 글로벌 유통'}, '건설': {'growth_drivers': '해외 수주 · 인프라 · 도시정비 · 친환경 건축', 'moat_pattern': '시공 실적 · 자본력 · 브랜드'}, '전력': {'growth_drivers': '전력 수요(데이터센터) · 요금 정상화 · 재생에너지', 'moat_pattern': '지역 독점 · 인프라 · 정부 보호'}, '철도': {'growth_drivers': '철도차량 수출 · 도시철도 · K-방산', 'moat_pattern': '기술 인증 · 장기 정부 발주 · 글로벌 실적'}, '항공': {'growth_drivers': '여객 수요 회복 · 화물 운임 · 노선 확장', 'moat_pattern': '노선권 · 슬롯 · 마일리지 락인'}, '해운': {'growth_drivers': '운임 사이클 · 친환경 선박 전환 · 노선 다변화', 'moat_pattern': '선대 규모 · 노선망 · 장기 계약'}, '지주사': {'growth_drivers': '자회사 가치 재평가 · 배당 확대 · 사업 재편', 'moat_pattern': '자회사 포트폴리오 · 지배구조 · 자본 동원력'}, 'IT서비스': {'growth_drivers': '디지털 전환 · 클라우드/AI 솔루션 · 그룹사 SI', 'moat_pattern': '그룹사 수요 기반 · 기술 인력 · 장기 계약'}, '핀테크': {'growth_drivers': '결제 시장 확대 · 데이터 활용 · 해외 진출', 'moat_pattern': '사용자 기반 · 결제 인프라 · 가맹점 네트워크'}, '중공업': {'growth_drivers': '글로벌 전력 인프라 · 해상풍력 · 수소 등 친환경', 'moat_pattern': '기술력 · 장기 수주잔고 · 글로벌 트랙레코드'}, '반도체장비': {'growth_drivers': 'AI 메모리 CAPEX · 첨단공정 전환 · 글로벌 수주', 'moat_pattern': '기술 특허 · 고객사 인증 · R&D 누적'}, '반도체소재': {'growth_drivers': '공정 미세화 · 신소재 채택 · 국산화 수요', 'moat_pattern': '공급사 인증 · 기술 진입장벽 · 안정 공급'}, '의료기기': {'growth_drivers': '고령화 · 글로벌 의료기기 수출 · 미용/필러', 'moat_pattern': '임상 데이터 · 인증 · 글로벌 유통'}, '제약': {'growth_drivers': '신약 R&D · 위탁생산(CMO) · 제네릭', 'moat_pattern': '특허 · 영업망 · R&D 파이프라인'}, '로봇': {'growth_drivers': '산업·서비스 로봇 수요 · 자동화 투자 · AI 결합', 'moat_pattern': '기술 격차 · 고객 레퍼런스 · 양산 능력'}, 'AI': {'growth_drivers': 'AI 인프라/솔루션 수요 · LLM 응용 · 데이터 분석', 'moat_pattern': '기술 인력 · 데이터 · 알고리즘 IP'}, '방산': {'growth_drivers': 'K-방산 수출 · 글로벌 안보 수요 · 우주항공', 'moat_pattern': '장기 정부 계약 · 기술 인증 · 양산 캐파'}}}
